#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDF5BA9D30642D5A0 (cifs-utils@samba.org)
#
Name     : cifs-utils
Version  : 6.8
Release  : 18
URL      : https://download.samba.org/pub/linux-cifs/cifs-utils/cifs-utils-6.8.tar.bz2
Source0  : https://download.samba.org/pub/linux-cifs/cifs-utils/cifs-utils-6.8.tar.bz2
Source99 : https://download.samba.org/pub/linux-cifs/cifs-utils/cifs-utils-6.8.tar.bz2.asc
Summary  : CIFS filesystem user-space tools
Group    : Development/Tools
License  : GPL-3.0
Requires: cifs-utils-bin = %{version}-%{release}
Requires: cifs-utils-lib = %{version}-%{release}
Requires: cifs-utils-license = %{version}-%{release}
Requires: cifs-utils-man = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : docutils
BuildRequires : keyutils-dev
BuildRequires : krb5-dev
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : sed

%description
As of version 1.5.5, prior to opening /etc/request-key.conf, the
request-key utility will look first in /etc/request-key.d for a file of
the key type name plus ".conf". These files are example config files
that distro packagers can use to have request-key autoconfigured to
use the cifs utilities that are installed. Typically, distro packagers
will want to drop the resulting .conf files into /etc/request-key.d.

%package bin
Summary: bin components for the cifs-utils package.
Group: Binaries
Requires: cifs-utils-license = %{version}-%{release}
Requires: cifs-utils-man = %{version}-%{release}

%description bin
bin components for the cifs-utils package.


%package dev
Summary: dev components for the cifs-utils package.
Group: Development
Requires: cifs-utils-lib = %{version}-%{release}
Requires: cifs-utils-bin = %{version}-%{release}
Provides: cifs-utils-devel = %{version}-%{release}

%description dev
dev components for the cifs-utils package.


%package lib
Summary: lib components for the cifs-utils package.
Group: Libraries
Requires: cifs-utils-license = %{version}-%{release}

%description lib
lib components for the cifs-utils package.


%package license
Summary: license components for the cifs-utils package.
Group: Default

%description license
license components for the cifs-utils package.


%package man
Summary: man components for the cifs-utils package.
Group: Default

%description man
man components for the cifs-utils package.


%prep
%setup -q -n cifs-utils-6.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549642836
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1549642836
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cifs-utils
cp COPYING %{buildroot}/usr/share/package-licenses/cifs-utils/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cifscreds
/usr/bin/mount.cifs

%files dev
%defattr(-,root,root,-)
/usr/include/*.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/security/pam_cifscreds.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cifs-utils/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cifscreds.1
/usr/share/man/man8/mount.cifs.8
/usr/share/man/man8/pam_cifscreds.8
